### ISSUE TITLE
JOSS Review - Blocking Issue - LICENSE File

### ISSUE THREAD

**Issue by rlizzo** [KVSlab/morphMan#11]
This is a Blocking issue for the project's JOSS Submission: https://github.com/openjournals/joss-reviews/issues/1065

Two things:

1) Remove the `.md` from the `LICENSE.md` file. It is important to have a pure plain text license file (which it not markdown formatted) for automated LICENSE finders to include appropriately. 

2) Please list the applicable licenses for VMTK / VTK / ITK (and other dependent projects), basically, copy paste (and modify where appropriate) the [VMTK LICENSE file](https://github.com/vmtk/vmtk/blob/master/LICENSE)

**Comment by aslakbergersen** [comment]
@rlizzo Thank you for pointing this out. We were actually a bit unsure on how to properly use the LICENSE. If you are pleased with the corrections we can close this issue.

Just to check, are the smaller version of the LICENCE on top of each file sufficient?

**Comment by rlizzo** [comment]
Hi @aslakbergersen, sorry for the late reply, yes it is sufficient. Closing due to completion of task! Thank you!
