### ISSUE TITLE
JOSS Review - Blocking Issue - Community Guidelines

### ISSUE THREAD

**Issue by rlizzo** [KVSlab/morphMan#13]
This is a blocking issue for the JOSS Review: https://github.com/openjournals/joss-reviews/issues/1065

The JOSS Submission Requires:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Please add documentation about how to set up an environment for development and/or guidelines on contributions. Preferably this would be in a separate `CONTRIBUTING.md` file.

**Comment by aslakbergersen** [comment]
@rlizzo, thank you for the comment. We have now added a `CONTRIBUTING.md` file, see [here.](https://github.com/KVSlab/morphMan/blob/master/CONTRIBUTING.md) If you find the changes to be satisfactory we can close this issue.

**Comment by rlizzo** [comment]
That's perfect Thank you! Closing the issue now!
