### ISSUE TITLE
Parameters should be stored as pickle or json format

### ISSUE THREAD

**Issue by aslakbergersen** [KVSlab/morphMan#5]
The [case_name]_info.txt file is now stored and read in a 'homemade' format style. To improve robustness this should be changed to json or pickle format instead.

@hkjeldsberg do you have any preferred choices or comments?

**Comment by rlizzo** [comment]
If you'd like an outsiders opinion, I would recommend JSON format for a number of reasons.

1) Its human readable: useful for the forgetful grad student who runs a ton of experiments - and who may have "dubious" experiment directory naming practices - to quickly view the parameters used for a given investigation via any text editor. 
2) Pickling in python is generally good at backwards compatibility, but has been known to get "weird" when an object is serialized in a newer python interpreter, and read in with an older interpreter. 
3) Any arbitrary python object can be serialized and stored via the pickle module. If the `info` file is truly only meant to store parameters, then you can enforce good development practices in the future by forcing JSON serialization. This format implicitly prevents future devs from being tempted store object state alongside experiment parameters in some "frankenstein monster" of an `info` file. Remember the Zen of Python: "Explicit is better than implicit".

**Comment by aslakbergersen** [comment]
Resolved with #26
