### ISSUE TITLE
TypeError: SetNumberOfComponents argument 1: an integer is required (got type vtkCommonDataModelPython.vtkPolyData)

### ISSUE THREAD

**Issue by MartinaSchena** [KVSlab/morphMan#59]
Hi,
I have a problem in running morphan methods, I have a .vtp file of an aneurysm and I want to modify the area. 
I use "morphman-area --ifile surface_remeshed.vtp --ofile surface_remeshed_increased.vtp --method variation --ratio 4 --region-of-interest manual --poly-ball-size 100 100 100
 " in anaconda prompt. 
It returns the following error: TypeError: SetNumberOfComponents argument 1: an integer is required (got type vtkCommonDataModelPython.vtkPolyData)
How can I solve?
![Cattura](https://user-images.githubusercontent.com/75420329/100990835-a4003700-3552-11eb-825f-f2578962d33f.PNG)
![Cattura1](https://user-images.githubusercontent.com/75420329/100991527-6354ed80-3553-11eb-9b67-3428870b95c4.PNG)
Thanks in advance

Martina

**Comment by aslakbergersen** [comment]
Hi @MartinaSchena,

Thanks for using morphMan!

I'm not able to reproduce your error, but I see you are running morphMan 0.3, could you try to install the 1.0 version and try again? If that does not work could you provide the python, vtk and vmtk version?

**Comment by MartinaSchena** [comment]
Hi @aslakbergersen 
thank you for your answer!
With the version 1.0 the error  doesn't appear anymore.
Best regards 

Martina
